# Generated by Django 5.0.4 on 2024-04-18 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomregister',
            old_name='fullname',
            new_name='fstname',
        ),
        migrations.AddField(
            model_name='ecomregister',
            name='lstname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
