# Generated by Django 5.0.4 on 2024-04-19 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_rename_fullname_ecomregister_fstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecomregister',
            old_name='fstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='ecomregister',
            name='lstname',
        ),
    ]
