# Generated by Django 5.0.4 on 2024-04-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_sellerproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerproduct',
            name='category',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
