# Generated by Django 5.0.4 on 2024-04-27 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selectedsize',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
